version: '3.8'
services:
  nsp_backend:
    container_name: nsp_backend
    image: atxpaul/nsp-template:0.0.1
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=atxpaul
      - PGPASSWORD=12345
      - PGDATABASE=nps_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=atxpaul
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nps_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
